# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcdb8a734cae0670d91709e125ccdd211039c203d8605f034737ea88ef1b561c6aeb8f0d7f08ae702e4d6750a0bb36272daa43c5aa9396f7aef5f552688aaa40

test:
  secret_key_base: 27b9cebb0c2a42621b3fa64e534d34f5a76c2379dd57ca84b5d46ccf58fc615ab4ada4a3d771c9db0cff79453fdb84669ed624c587b73a0953dc80ecaece6417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
